name: Terraform Go CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'
      - name: Install dependencies
        run: |
          go version
          go get -u "github.com/gruntwork-io/terratest/modules/terraform"
      - name: Run build
        run: go build .
      - name: Run testing
        run: cd test && go test -v

